# Automated enhanced learning system with VAK learning style detection using  Machine Learning

* Classification will be done on the basis of score recorded from the responses of the users.

In [1]:
import pandas as py
import sklearn as skl
import matplotlib.pyplot as plt
import numpy as np
import sys
import scipy

In [2]:
df = py.read_csv("D:/Academics/Mini Projects/MIni Project 1/Data/vak.csv",header=0)

In [3]:
df.head()

1  2  3  4  5  6  7  8  9  10  ...  22  23  24  25  26  27  28  29  30  \
0  3  2  2  3  2  2  1  2  1   3  ...   1   1   1   3   3   3   3   1   1   
1  1  2  2  3  1  3  3  3  3   1  ...   1   3   1   1   1   1   3   2   1   
2  1  2  1  3  1  2  1  3  2   2  ...   3   1   2   1   1   3   2   2   3   
3  3  1  1  3  1  1  3  1  2   3  ...   3   3   2   3   1   1   3   1   1   
4  3  1  1  2  1  3  3  3  3   3  ...   2   2   2   1   1   3   2   1   2   

                 31  
0       Kinesthetic  
1  Visual, Auditory  
2            Visual  
3       Kinesthetic  
4          Auditory  

[5 rows x 31 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 922 entries, 0 to 921
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   1       922 non-null    int64 
 1   2       922 non-null    int64 
 2   3       922 non-null    int64 
 3   4       922 non-null    int64 
 4   5       922 non-null    int64 
 5   6       922 non-null    int64 
 6   7       922 non-null    int64 
 7   8       922 non-null    int64 
 8   9       922 non-null    int64 
 9   10      922 non-null    int64 
 10  11      922 non-null    int64 
 11  12      922 non-null    int64 
 12  13      922 non-null    int64 
 13  14      922 non-null    int64 
 14  15      922 non-null    int64 
 15  16      922 non-null    int64 
 16  17      922 non-null    int64 
 17  18      922 non-null    int64 
 18  19      922 non-null    int64 
 19  20      922 non-null    int64 
 20  21      922 non-null    int64 
 21  22      922 non-null    int64 
 22  23      922 non-null    in

# X-Y split

In [5]:
X = df.loc[:,df.columns!="31"]
type(X)

pandas.core.frame.DataFrame

In [6]:
X.head()

1  2  3  4  5  6  7  8  9  10  ...  21  22  23  24  25  26  27  28  29  30
0  3  2  2  3  2  2  1  2  1   3  ...   1   1   1   1   3   3   3   3   1   1
1  1  2  2  3  1  3  3  3  3   1  ...   1   1   3   1   1   1   1   3   2   1
2  1  2  1  3  1  2  1  3  2   2  ...   1   3   1   2   1   1   3   2   2   3
3  3  1  1  3  1  1  3  1  2   3  ...   2   3   3   2   3   1   1   3   1   1
4  3  1  1  2  1  3  3  3  3   3  ...   3   2   2   2   1   1   3   2   1   2

[5 rows x 30 columns]

In [7]:
X.shape

(922, 30)

In [8]:
Y = df["31"]
type(Y)

pandas.core.series.Series

In [9]:
Y.head()

0         Kinesthetic
1    Visual, Auditory
2              Visual
3         Kinesthetic
4            Auditory
Name: 31, dtype: object

In [10]:
Y.shape

(922,)

# Test-Train split

* 80% will be the training data and 20% will be the testing data

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25,random_state=0)

In [13]:
X_train.head()

1  2  3  4  5  6  7  8  9  10  ...  21  22  23  24  25  26  27  28  29  \
524  3  3  2  1  1  1  1  2  3   1  ...   1   2   2   2   2   1   3   1   1   
39   1  1  1  1  2  2  3  3  3   3  ...   3   1   1   1   2   1   3   1   1   
319  1  1  3  1  2  3  3  3  3   2  ...   3   1   2   1   3   3   1   1   2   
910  2  3  1  2  2  1  1  3  1   2  ...   1   3   1   3   1   3   1   2   1   
18   2  1  2  1  3  3  3  3  2   1  ...   2   1   1   2   2   1   3   3   2   

     30  
524   1  
39    2  
319   2  
910   1  
18    2  

[5 rows x 30 columns]

In [14]:
Y_train.head()

524                 Auditory
39       Visual, Kinesthetic
319    Auditory, Kinesthetic
910              Kinesthetic
18                  Auditory
Name: 31, dtype: object

In [15]:
X_train.shape

(691, 30)

In [16]:
Y_train.shape

(691,)

In [17]:
X_test.head()

1  2  3  4  5  6  7  8  9  10  ...  21  22  23  24  25  26  27  28  29  \
608  1  3  2  2  1  2  1  2  3   1  ...   3   3   3   2   1   2   2   3   3   
350  1  1  2  1  3  3  3  2  3   2  ...   2   1   1   2   1   3   3   3   1   
299  1  1  1  1  1  2  3  3  2   3  ...   1   1   1   1   1   3   2   2   3   
726  3  3  1  3  2  1  1  1  3   2  ...   1   3   2   3   2   2   3   2   3   
253  1  1  3  1  1  2  3  1  3   2  ...   3   2   2   1   3   1   3   1   2   

     30  
608   2  
350   3  
299   3  
726   3  
253   3  

[5 rows x 30 columns]

In [18]:
X_test.shape

(231, 30)

In [19]:
Y_test.head()

608            Kinesthetic
350            Kinesthetic
299                 Visual
726    Visual, Kinesthetic
253            Kinesthetic
Name: 31, dtype: object

In [20]:
Y_test.shape

(231,)

# Training Model

* Train model

In [21]:
from sklearn import svm

In [22]:
clf_svm_1 = svm.SVC()
clf_svm_1.fit(X_train,Y_train)

SVC()

* Predict values using train model

In [23]:
y_train_pred = clf_svm_1.predict(X_train)
y_test_pred = clf_svm_1.predict(X_test)

In [24]:
y_test_pred

array(['Kinesthetic', 'Kinesthetic', 'Visual', 'Kinesthetic',
       'Kinesthetic', 'Auditory', 'Kinesthetic', 'Visual', 'Visual',
       'Auditory', 'Auditory', 'Visual', 'Auditory', 'Kinesthetic',
       'Auditory', 'Auditory', 'Auditory', 'Auditory', 'Visual',
       'Auditory', 'Visual', 'Kinesthetic', 'Visual', 'Auditory',
       'Kinesthetic', 'Kinesthetic', 'Kinesthetic', 'Kinesthetic',
       'Visual', 'Kinesthetic', 'Kinesthetic', 'Auditory', 'Kinesthetic',
       'Visual', 'Visual', 'Visual', 'Kinesthetic', 'Visual', 'Auditory',
       'Auditory', 'Visual', 'Auditory', 'Auditory', 'Kinesthetic',
       'Auditory', 'Auditory', 'Visual', 'Kinesthetic', 'Auditory',
       'Kinesthetic', 'Kinesthetic', 'Visual', 'Auditory', 'Kinesthetic',
       'Auditory', 'Kinesthetic', 'Kinesthetic', 'Auditory', 'Auditory',
       'Visual', 'Kinesthetic', 'Visual', 'Auditory', 'Kinesthetic',
       'Visual', 'Kinesthetic', 'Visual', 'Kinesthetic', 'Visual',
       'Auditory', 'Auditory', 'Kine

# Model Performance

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [26]:
confusion_matrix(Y_test,y_test_pred)

array([[41,  0, 21, 12,  0,  0,  0],
       [ 1,  0,  2,  0,  0,  0,  0],
       [ 6,  0, 57,  7,  0,  0,  0],
       [15,  0, 10, 45,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0,  0,  0],
       [ 2,  0,  5,  2,  0,  0,  0]], dtype=int64)

In [27]:
accuracy_score(Y_test,y_test_pred)

0.6190476190476191

In [28]:
from sklearn.metrics import classification_report

In [29]:
print(accuracy_score(Y_test, y_test_pred))
print(confusion_matrix(Y_test, y_test_pred))
print(classification_report(Y_test, y_test_pred))

0.6190476190476191
[[41  0 21 12  0  0  0]
 [ 1  0  2  0  0  0  0]
 [ 6  0 57  7  0  0  0]
 [15  0 10 45  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0]
 [ 2  0  5  2  0  0  0]]
                               precision    recall  f1-score   support

                     Auditory       0.59      0.55      0.57        74
        Auditory, Kinesthetic       0.00      0.00      0.00         3
                  Kinesthetic       0.60      0.81      0.69        70
                       Visual       0.68      0.64      0.66        70
             Visual, Auditory       0.00      0.00      0.00         2
Visual, Auditory, Kinesthetic       0.00      0.00      0.00         3
          Visual, Kinesthetic       0.00      0.00      0.00         9

                     accuracy                           0.62       231
                    macro avg       0.27      0.29      0.27       231
                 weighted avg       0.58      0.62      0.59       231



C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
clf_svm_1.n_support_

array([199,  22, 247, 163,  11,   9,  19,   2,   2,   1,   1])

# Gaussian NB 

In [34]:
from sklearn.naive_bayes import GaussianNB

In [41]:
nb = GaussianNB()
nb.fit(X_train, Y_train)
predictions = nb.predict(X_test)

In [42]:
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

0.5757575757575758
[[28  0 30 14  1  1  0]
 [ 1  0  2  0  0  0  0]
 [ 4  0 60  5  0  1  0]
 [14  0 11 45  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0]
 [ 2  0  4  3  0  0  0]]
                               precision    recall  f1-score   support

                     Auditory       0.52      0.38      0.44        74
        Auditory, Kinesthetic       0.00      0.00      0.00         3
                  Kinesthetic       0.56      0.86      0.68        70
                       Visual       0.67      0.64      0.66        70
             Visual, Auditory       0.00      0.00      0.00         2
Visual, Auditory, Kinesthetic       0.00      0.00      0.00         3
          Visual, Kinesthetic       0.00      0.00      0.00         9

                     accuracy                           0.58       231
                    macro avg       0.25      0.27      0.25       231
                 weighted avg       0.54      0.58      0.54       231



C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# LDA

In [43]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [44]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, Y_train)
predictions = lda.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

0.48917748917748916
[[22  0 32 19  0  1  0]
 [ 1  0  2  0  0  0  0]
 [17  0 48  4  0  1  0]
 [21  0  5 43  0  0  1]
 [ 1  0  0  1  0  0  0]
 [ 3  0  0  0  0  0  0]
 [ 3  0  4  2  0  0  0]]
                               precision    recall  f1-score   support

                     Auditory       0.32      0.30      0.31        74
        Auditory, Kinesthetic       0.00      0.00      0.00         3
                  Kinesthetic       0.53      0.69      0.60        70
                       Visual       0.62      0.61      0.62        70
             Visual, Auditory       0.00      0.00      0.00         2
Visual, Auditory, Kinesthetic       0.00      0.00      0.00         3
          Visual, Kinesthetic       0.00      0.00      0.00         9

                     accuracy                           0.49       231
                    macro avg       0.21      0.23      0.22       231
                 weighted avg       0.45      0.49      0.47       231



C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PIYUSH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Testing for single data

In [1]:
new_input = [[1,2,3,1,2,3,1,1,1,1,1,1,1,1,3,2,1,1,1,1,1,1,1,1,1,1,1,2,2,1]]